/*
 * This Java source file was generated by the Gradle 'init' task.
 * https://thiscouldbebetter.wordpress.com/2011/09/04/sending-an-email-from-java-using-jmail-and-apache-james/
 */
package io.crtp.email2txt;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
//import java.lang.Exception.MessagingException;
import javax.mail.Transport;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        //String addressee = args[0];
        String addressee = "greeneh@gmail.com";

        EmailMessage emailMessage = new EmailMessage ( "cf2141@tgndomains.com",
                                                        addressee,
                                                        "test email",
                                                        "This is a test email." );

        emailMessage.send();
        System.out.println("email message sent to " + addressee);

    }
}


class EmailMessage {

    public String sender;
    public String addressee;
    public String subject;
    public String body;

    public EmailMessage ( String sender,
                            String addressee,
                            String subject,
                            String body ) {

        this.sender = sender;
        this.addressee = addressee;
        this.subject = subject;
        this.body = body;

    }

    public void send() {

        String port = "25";
        //String port = "110"
        System.out.println(port);

        Properties mailServerProperties = new Properties();
        mailServerProperties.put ( "mail.smtp.host", "mail.tgndomains.com" );
        mailServerProperties.put ( "mail.smtp.port", port );

        Session session = Session.getDefaultInstance( mailServerProperties );

        MimeMessage messageToSend = new MimeMessage(session);

        try {
            messageToSend.setFrom ( new InternetAddress(this.sender) );
            messageToSend.addRecipient ( Message.RecipientType.TO,
                                         new InternetAddress(this.addressee) );

            messageToSend.setSubject(this.subject);
            messageToSend.setText(this.body);

            //Transport.send(messageToSend);

            Transport tr = 

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
